export const CAPTIONS = {
  ENVIRONMENT_CHECK: 'Проверка окружения перед запуском демонстрации',
  LOGIN: 'Входим в NordiPass как администратор компании',
  MENU_TOUR_START: 'Обзор интерфейса NordiPass',
  MENU_TOUR_DONE: 'Все разделы открыты без ошибок',
  BUSINESS_START: 'Теперь создадим реальный продукт от начала до публикации',
  CREATE_CATEGORY_ROOT: 'Создание корневой категории',
  CREATE_CATEGORY_CHILD: 'Создание дочерней категории',
  CATEGORY_DONE: 'Каталог поддерживает иерархию категорий',
  CREATE_ATTRIBUTES: 'Добавление характеристик товара',
  ATTRIBUTES_DONE: 'Характеристики созданы',
  CREATE_PRODUCT: 'Создаём новый товар',
  PRODUCT_SAVED: 'Черновик товара сохранён',
  PRODUCT_ATTRIBUTES: 'Заполнение характеристик товара',
  CREATE_VARIANTS: 'Создание товарных вариантов',
  VARIANTS_DONE: 'Варианты созданы: M, L, XL — Active',
  UPLOAD_IMAGES: 'Загрузка изображений товара',
  IMAGES_DONE: 'Изображения загружены',
  UPLOAD_DOCUMENTS: 'Загрузка документов',
  DOCUMENTS_DONE: 'Документы загружены',
  PASSPORT_FILL: 'Заполнение информации Digital Product Passport',
  PREVIEW_CHECK: 'Проверяем данные перед публикацией',
  PUBLISH: 'Публикация продукта',
  PUBLISHED: 'Товар опубликован и доступен покупателям',
  QR_SHOW: 'QR-код продукта',
  PUBLIC_PAGE: 'Проверка публичной страницы',
  COMPLETE: 'NordiPass demonstration completed',
};
